// Code generated by mockery v2.46.3. DO NOT EDIT.

package models

import (
	mock "github.com/stretchr/testify/mock"
	models "gophkeeper.com/internal/server/models"
)

// SecretOption is an autogenerated mock type for the SecretOption type
type SecretOption struct {
	mock.Mock
}

type SecretOption_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretOption) EXPECT() *SecretOption_Expecter {
	return &SecretOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *SecretOption) Execute(_a0 *models.SecretOptions) {
	_m.Called(_a0)
}

// SecretOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SecretOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *models.SecretOptions
func (_e *SecretOption_Expecter) Execute(_a0 interface{}) *SecretOption_Execute_Call {
	return &SecretOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *SecretOption_Execute_Call) Run(run func(_a0 *models.SecretOptions)) *SecretOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.SecretOptions))
	})
	return _c
}

func (_c *SecretOption_Execute_Call) Return() *SecretOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *SecretOption_Execute_Call) RunAndReturn(run func(*models.SecretOptions)) *SecretOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecretOption creates a new instance of SecretOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretOption {
	mock := &SecretOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
