// Code generated by mockery v2.46.3. DO NOT EDIT.

package operation

import (
	mock "github.com/stretchr/testify/mock"
	models "gophkeeper.com/internal/server/models"
)

// Creater is an autogenerated mock type for the Creater type
type Creater struct {
	mock.Mock
}

type Creater_Expecter struct {
	mock *mock.Mock
}

func (_m *Creater) EXPECT() *Creater_Expecter {
	return &Creater_Expecter{mock: &_m.Mock}
}

// VisitBinary provides a mock function with given fields: _a0
func (_m *Creater) VisitBinary(_a0 *models.Binary) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitBinary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Binary) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Creater_VisitBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitBinary'
type Creater_VisitBinary_Call struct {
	*mock.Call
}

// VisitBinary is a helper method to define mock.On call
//   - _a0 *models.Binary
func (_e *Creater_Expecter) VisitBinary(_a0 interface{}) *Creater_VisitBinary_Call {
	return &Creater_VisitBinary_Call{Call: _e.mock.On("VisitBinary", _a0)}
}

func (_c *Creater_VisitBinary_Call) Run(run func(_a0 *models.Binary)) *Creater_VisitBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Binary))
	})
	return _c
}

func (_c *Creater_VisitBinary_Call) Return(_a0 error) *Creater_VisitBinary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Creater_VisitBinary_Call) RunAndReturn(run func(*models.Binary) error) *Creater_VisitBinary_Call {
	_c.Call.Return(run)
	return _c
}

// VisitCard provides a mock function with given fields: _a0
func (_m *Creater) VisitCard(_a0 *models.Card) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Card) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Creater_VisitCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitCard'
type Creater_VisitCard_Call struct {
	*mock.Call
}

// VisitCard is a helper method to define mock.On call
//   - _a0 *models.Card
func (_e *Creater_Expecter) VisitCard(_a0 interface{}) *Creater_VisitCard_Call {
	return &Creater_VisitCard_Call{Call: _e.mock.On("VisitCard", _a0)}
}

func (_c *Creater_VisitCard_Call) Run(run func(_a0 *models.Card)) *Creater_VisitCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Card))
	})
	return _c
}

func (_c *Creater_VisitCard_Call) Return(_a0 error) *Creater_VisitCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Creater_VisitCard_Call) RunAndReturn(run func(*models.Card) error) *Creater_VisitCard_Call {
	_c.Call.Return(run)
	return _c
}

// VisitLogin provides a mock function with given fields: _a0
func (_m *Creater) VisitLogin(_a0 *models.Login) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Login) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Creater_VisitLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitLogin'
type Creater_VisitLogin_Call struct {
	*mock.Call
}

// VisitLogin is a helper method to define mock.On call
//   - _a0 *models.Login
func (_e *Creater_Expecter) VisitLogin(_a0 interface{}) *Creater_VisitLogin_Call {
	return &Creater_VisitLogin_Call{Call: _e.mock.On("VisitLogin", _a0)}
}

func (_c *Creater_VisitLogin_Call) Run(run func(_a0 *models.Login)) *Creater_VisitLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Login))
	})
	return _c
}

func (_c *Creater_VisitLogin_Call) Return(_a0 error) *Creater_VisitLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Creater_VisitLogin_Call) RunAndReturn(run func(*models.Login) error) *Creater_VisitLogin_Call {
	_c.Call.Return(run)
	return _c
}

// VisitNote provides a mock function with given fields: _a0
func (_m *Creater) VisitNote(_a0 *models.Note) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Note) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Creater_VisitNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitNote'
type Creater_VisitNote_Call struct {
	*mock.Call
}

// VisitNote is a helper method to define mock.On call
//   - _a0 *models.Note
func (_e *Creater_Expecter) VisitNote(_a0 interface{}) *Creater_VisitNote_Call {
	return &Creater_VisitNote_Call{Call: _e.mock.On("VisitNote", _a0)}
}

func (_c *Creater_VisitNote_Call) Run(run func(_a0 *models.Note)) *Creater_VisitNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *Creater_VisitNote_Call) Return(_a0 error) *Creater_VisitNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Creater_VisitNote_Call) RunAndReturn(run func(*models.Note) error) *Creater_VisitNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreater creates a new instance of Creater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creater {
	mock := &Creater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
