// Code generated by mockery v2.46.3. DO NOT EDIT.

package operation

import (
	mock "github.com/stretchr/testify/mock"

	models "github.com/itallix/gophkeeper/internal/server/models"
)

// Lister is an autogenerated mock type for the Lister type
type Lister struct {
	mock.Mock
}

type Lister_Expecter struct {
	mock *mock.Mock
}

func (_m *Lister) EXPECT() *Lister_Expecter {
	return &Lister_Expecter{mock: &_m.Mock}
}

// VisitBinary provides a mock function with given fields: _a0
func (_m *Lister) VisitBinary(_a0 *models.Binary) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitBinary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Binary) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lister_VisitBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitBinary'
type Lister_VisitBinary_Call struct {
	*mock.Call
}

// VisitBinary is a helper method to define mock.On call
//   - _a0 *models.Binary
func (_e *Lister_Expecter) VisitBinary(_a0 interface{}) *Lister_VisitBinary_Call {
	return &Lister_VisitBinary_Call{Call: _e.mock.On("VisitBinary", _a0)}
}

func (_c *Lister_VisitBinary_Call) Run(run func(_a0 *models.Binary)) *Lister_VisitBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Binary))
	})
	return _c
}

func (_c *Lister_VisitBinary_Call) Return(_a0 error) *Lister_VisitBinary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Lister_VisitBinary_Call) RunAndReturn(run func(*models.Binary) error) *Lister_VisitBinary_Call {
	_c.Call.Return(run)
	return _c
}

// VisitCard provides a mock function with given fields: _a0
func (_m *Lister) VisitCard(_a0 *models.Card) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Card) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lister_VisitCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitCard'
type Lister_VisitCard_Call struct {
	*mock.Call
}

// VisitCard is a helper method to define mock.On call
//   - _a0 *models.Card
func (_e *Lister_Expecter) VisitCard(_a0 interface{}) *Lister_VisitCard_Call {
	return &Lister_VisitCard_Call{Call: _e.mock.On("VisitCard", _a0)}
}

func (_c *Lister_VisitCard_Call) Run(run func(_a0 *models.Card)) *Lister_VisitCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Card))
	})
	return _c
}

func (_c *Lister_VisitCard_Call) Return(_a0 error) *Lister_VisitCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Lister_VisitCard_Call) RunAndReturn(run func(*models.Card) error) *Lister_VisitCard_Call {
	_c.Call.Return(run)
	return _c
}

// VisitLogin provides a mock function with given fields: _a0
func (_m *Lister) VisitLogin(_a0 *models.Login) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Login) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lister_VisitLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitLogin'
type Lister_VisitLogin_Call struct {
	*mock.Call
}

// VisitLogin is a helper method to define mock.On call
//   - _a0 *models.Login
func (_e *Lister_Expecter) VisitLogin(_a0 interface{}) *Lister_VisitLogin_Call {
	return &Lister_VisitLogin_Call{Call: _e.mock.On("VisitLogin", _a0)}
}

func (_c *Lister_VisitLogin_Call) Run(run func(_a0 *models.Login)) *Lister_VisitLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Login))
	})
	return _c
}

func (_c *Lister_VisitLogin_Call) Return(_a0 error) *Lister_VisitLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Lister_VisitLogin_Call) RunAndReturn(run func(*models.Login) error) *Lister_VisitLogin_Call {
	_c.Call.Return(run)
	return _c
}

// VisitNote provides a mock function with given fields: _a0
func (_m *Lister) VisitNote(_a0 *models.Note) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Note) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lister_VisitNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitNote'
type Lister_VisitNote_Call struct {
	*mock.Call
}

// VisitNote is a helper method to define mock.On call
//   - _a0 *models.Note
func (_e *Lister_Expecter) VisitNote(_a0 interface{}) *Lister_VisitNote_Call {
	return &Lister_VisitNote_Call{Call: _e.mock.On("VisitNote", _a0)}
}

func (_c *Lister_VisitNote_Call) Run(run func(_a0 *models.Note)) *Lister_VisitNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *Lister_VisitNote_Call) Return(_a0 error) *Lister_VisitNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Lister_VisitNote_Call) RunAndReturn(run func(*models.Note) error) *Lister_VisitNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewLister creates a new instance of Lister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *Lister {
	mock := &Lister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
