// Code generated by mockery v2.46.3. DO NOT EDIT.

package operation

import (
	mock "github.com/stretchr/testify/mock"
	models "gophkeeper.com/internal/server/models"
)

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

type Updater_Expecter struct {
	mock *mock.Mock
}

func (_m *Updater) EXPECT() *Updater_Expecter {
	return &Updater_Expecter{mock: &_m.Mock}
}

// VisitBinary provides a mock function with given fields: _a0
func (_m *Updater) VisitBinary(_a0 *models.Binary) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitBinary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Binary) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updater_VisitBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitBinary'
type Updater_VisitBinary_Call struct {
	*mock.Call
}

// VisitBinary is a helper method to define mock.On call
//   - _a0 *models.Binary
func (_e *Updater_Expecter) VisitBinary(_a0 interface{}) *Updater_VisitBinary_Call {
	return &Updater_VisitBinary_Call{Call: _e.mock.On("VisitBinary", _a0)}
}

func (_c *Updater_VisitBinary_Call) Run(run func(_a0 *models.Binary)) *Updater_VisitBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Binary))
	})
	return _c
}

func (_c *Updater_VisitBinary_Call) Return(_a0 error) *Updater_VisitBinary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Updater_VisitBinary_Call) RunAndReturn(run func(*models.Binary) error) *Updater_VisitBinary_Call {
	_c.Call.Return(run)
	return _c
}

// VisitCard provides a mock function with given fields: _a0
func (_m *Updater) VisitCard(_a0 *models.Card) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Card) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updater_VisitCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitCard'
type Updater_VisitCard_Call struct {
	*mock.Call
}

// VisitCard is a helper method to define mock.On call
//   - _a0 *models.Card
func (_e *Updater_Expecter) VisitCard(_a0 interface{}) *Updater_VisitCard_Call {
	return &Updater_VisitCard_Call{Call: _e.mock.On("VisitCard", _a0)}
}

func (_c *Updater_VisitCard_Call) Run(run func(_a0 *models.Card)) *Updater_VisitCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Card))
	})
	return _c
}

func (_c *Updater_VisitCard_Call) Return(_a0 error) *Updater_VisitCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Updater_VisitCard_Call) RunAndReturn(run func(*models.Card) error) *Updater_VisitCard_Call {
	_c.Call.Return(run)
	return _c
}

// VisitLogin provides a mock function with given fields: _a0
func (_m *Updater) VisitLogin(_a0 *models.Login) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Login) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updater_VisitLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitLogin'
type Updater_VisitLogin_Call struct {
	*mock.Call
}

// VisitLogin is a helper method to define mock.On call
//   - _a0 *models.Login
func (_e *Updater_Expecter) VisitLogin(_a0 interface{}) *Updater_VisitLogin_Call {
	return &Updater_VisitLogin_Call{Call: _e.mock.On("VisitLogin", _a0)}
}

func (_c *Updater_VisitLogin_Call) Run(run func(_a0 *models.Login)) *Updater_VisitLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Login))
	})
	return _c
}

func (_c *Updater_VisitLogin_Call) Return(_a0 error) *Updater_VisitLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Updater_VisitLogin_Call) RunAndReturn(run func(*models.Login) error) *Updater_VisitLogin_Call {
	_c.Call.Return(run)
	return _c
}

// VisitNote provides a mock function with given fields: _a0
func (_m *Updater) VisitNote(_a0 *models.Note) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Note) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updater_VisitNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitNote'
type Updater_VisitNote_Call struct {
	*mock.Call
}

// VisitNote is a helper method to define mock.On call
//   - _a0 *models.Note
func (_e *Updater_Expecter) VisitNote(_a0 interface{}) *Updater_VisitNote_Call {
	return &Updater_VisitNote_Call{Call: _e.mock.On("VisitNote", _a0)}
}

func (_c *Updater_VisitNote_Call) Run(run func(_a0 *models.Note)) *Updater_VisitNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *Updater_VisitNote_Call) Return(_a0 error) *Updater_VisitNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Updater_VisitNote_Call) RunAndReturn(run func(*models.Note) error) *Updater_VisitNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
