CREATE TABLE IF NOT EXISTS "secrets" (
	"secret_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"path" VARCHAR(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL DEFAULT(now()),
	"modified_at" TIMESTAMP NOT NULL DEFAULT(now()),
	"custom_metadata" JSON,
	"encrypted_data_key" BYTEA NOT NULL,
	"created_by" VARCHAR(255),
	"modified_by" VARCHAR(255),
	PRIMARY KEY("secret_id")
);


CREATE TABLE IF NOT EXISTS "logins" (
	"login_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"secret_id" INTEGER NOT NULL,
	"login" VARCHAR(255) NOT NULL,
	"password" BYTEA NOT NULL,
	PRIMARY KEY("login_id", "secret_id")
);


CREATE TABLE IF NOT EXISTS "cards" (
	"card_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"secret_id" INTEGER NOT NULL,
	"cardholder_name" VARCHAR(255) NOT NULL,
	"number" BYTEA NOT NULL,
	"expiry_month" SMALLINT NOT NULL,
    "expiry_year" SMALLINT NOT NULL,
	"cvc" BYTEA NOT NULL,
	PRIMARY KEY("card_id", "secret_id")
);


CREATE TABLE IF NOT EXISTS "notes" (
	"note_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"secret_id" INTEGER NOT NULL,
	"text" BYTEA,
	PRIMARY KEY("note_id", "secret_id")
);


CREATE TABLE IF NOT EXISTS "binaries" (
	"binary_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"secret_id" INTEGER NOT NULL,
	"chunks" SMALLINT,
	"hash" VARCHAR(255),
	PRIMARY KEY("binary_id", "secret_id")
);


CREATE TABLE IF NOT EXISTS "users" (
	"login" VARCHAR(255) NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT(now()),
	"modified_at" TIMESTAMP NOT NULL DEFAULT(now()),
	PRIMARY KEY("login")
);


ALTER TABLE "logins"
ADD FOREIGN KEY("secret_id") REFERENCES "secrets"("secret_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "cards"
ADD FOREIGN KEY("secret_id") REFERENCES "secrets"("secret_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "notes"
ADD FOREIGN KEY("secret_id") REFERENCES "secrets"("secret_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "binaries"
ADD FOREIGN KEY("secret_id") REFERENCES "secrets"("secret_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "secrets"
ADD FOREIGN KEY("created_by") REFERENCES "users"("login")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "secrets"
ADD FOREIGN KEY("modified_by") REFERENCES "users"("login")
ON UPDATE NO ACTION ON DELETE CASCADE;
