coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 1%
        base: auto
ignore:
  - "mocks/"
  - "cmd/"
  - "pkg/"
  - "internal/server/grpc"
  - "internal/server/migration.go"
  - "internal/server/operation/processor.go"
  - "internal/common"
  - "internal/client/grpc"
  - "internal/client/app.go"
  - "internal/client/cmd/binary.go"
  - "internal/client/cmd/config.go"
  - "internal/client/cmd/prompt.go"
