with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/itallix/gophkeeper/internal/server:
    config:
      recursive: True
  github.com/itallix/gophkeeper/pkg/generated/api/proto/v1:
    config:
      recursive: True
