// Code generated by mockery v2.46.3. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "gophkeeper.com/internal/server/service"
)

// AuthenticationService is an autogenerated mock type for the AuthenticationService type
type AuthenticationService struct {
	mock.Mock
}

type AuthenticationService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationService) EXPECT() *AuthenticationService_Expecter {
	return &AuthenticationService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, username, password
func (_m *AuthenticationService) Authenticate(ctx context.Context, username string, password string) (*service.TokenPair, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*service.TokenPair, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *service.TokenPair); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type AuthenticationService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthenticationService_Expecter) Authenticate(ctx interface{}, username interface{}, password interface{}) *AuthenticationService_Authenticate_Call {
	return &AuthenticationService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, username, password)}
}

func (_c *AuthenticationService_Authenticate_Call) Run(run func(ctx context.Context, username string, password string)) *AuthenticationService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthenticationService_Authenticate_Call) Return(_a0 *service.TokenPair, _a1 error) *AuthenticationService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (*service.TokenPair, error)) *AuthenticationService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenPair provides a mock function with given fields: username
func (_m *AuthenticationService) GetTokenPair(username string) (*service.TokenPair, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenPair")
	}

	var r0 *service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.TokenPair, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *service.TokenPair); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_GetTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenPair'
type AuthenticationService_GetTokenPair_Call struct {
	*mock.Call
}

// GetTokenPair is a helper method to define mock.On call
//   - username string
func (_e *AuthenticationService_Expecter) GetTokenPair(username interface{}) *AuthenticationService_GetTokenPair_Call {
	return &AuthenticationService_GetTokenPair_Call{Call: _e.mock.On("GetTokenPair", username)}
}

func (_c *AuthenticationService_GetTokenPair_Call) Run(run func(username string)) *AuthenticationService_GetTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthenticationService_GetTokenPair_Call) Return(_a0 *service.TokenPair, _a1 error) *AuthenticationService_GetTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_GetTokenPair_Call) RunAndReturn(run func(string) (*service.TokenPair, error)) *AuthenticationService_GetTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: refreshToken
func (_m *AuthenticationService) RefreshTokens(refreshToken string) (*service.TokenPair, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.TokenPair, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *service.TokenPair); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type AuthenticationService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - refreshToken string
func (_e *AuthenticationService_Expecter) RefreshTokens(refreshToken interface{}) *AuthenticationService_RefreshTokens_Call {
	return &AuthenticationService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", refreshToken)}
}

func (_c *AuthenticationService_RefreshTokens_Call) Run(run func(refreshToken string)) *AuthenticationService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthenticationService_RefreshTokens_Call) Return(_a0 *service.TokenPair, _a1 error) *AuthenticationService_RefreshTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_RefreshTokens_Call) RunAndReturn(run func(string) (*service.TokenPair, error)) *AuthenticationService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: accessToken
func (_m *AuthenticationService) ValidateAccessToken(accessToken string) (string, error) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(accessToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(accessToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type AuthenticationService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - accessToken string
func (_e *AuthenticationService_Expecter) ValidateAccessToken(accessToken interface{}) *AuthenticationService_ValidateAccessToken_Call {
	return &AuthenticationService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", accessToken)}
}

func (_c *AuthenticationService_ValidateAccessToken_Call) Run(run func(accessToken string)) *AuthenticationService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthenticationService_ValidateAccessToken_Call) Return(_a0 string, _a1 error) *AuthenticationService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_ValidateAccessToken_Call) RunAndReturn(run func(string) (string, error)) *AuthenticationService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticationService creates a new instance of AuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationService {
	mock := &AuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
