// Code generated by mockery v2.46.3. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// AuthenticationService is an autogenerated mock type for the AuthenticationService type
type AuthenticationService struct {
	mock.Mock
}

type AuthenticationService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationService) EXPECT() *AuthenticationService_Expecter {
	return &AuthenticationService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: username, password
func (_m *AuthenticationService) Authenticate(username string, password string) (string, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type AuthenticationService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *AuthenticationService_Expecter) Authenticate(username interface{}, password interface{}) *AuthenticationService_Authenticate_Call {
	return &AuthenticationService_Authenticate_Call{Call: _e.mock.On("Authenticate", username, password)}
}

func (_c *AuthenticationService_Authenticate_Call) Run(run func(username string, password string)) *AuthenticationService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthenticationService_Authenticate_Call) Return(_a0 string, _a1 error) *AuthenticationService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_Authenticate_Call) RunAndReturn(run func(string, string) (string, error)) *AuthenticationService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *AuthenticationService) ValidateToken(token string) (bool, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type AuthenticationService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *AuthenticationService_Expecter) ValidateToken(token interface{}) *AuthenticationService_ValidateToken_Call {
	return &AuthenticationService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *AuthenticationService_ValidateToken_Call) Run(run func(token string)) *AuthenticationService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthenticationService_ValidateToken_Call) Return(_a0 bool, _a1 error) *AuthenticationService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationService_ValidateToken_Call) RunAndReturn(run func(string) (bool, error)) *AuthenticationService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticationService creates a new instance of AuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationService {
	mock := &AuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
