// Code generated by mockery v2.46.3. DO NOT EDIT.

package service

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// EncryptionService is an autogenerated mock type for the EncryptionService type
type EncryptionService struct {
	mock.Mock
}

type EncryptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *EncryptionService) EXPECT() *EncryptionService_Expecter {
	return &EncryptionService_Expecter{mock: &_m.Mock}
}

// DecryptStream provides a mock function with given fields: src, dst, encryptedDataKey
func (_m *EncryptionService) DecryptStream(src io.Reader, dst io.Writer, encryptedDataKey []byte) error {
	ret := _m.Called(src, dst, encryptedDataKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, io.Writer, []byte) error); ok {
		r0 = rf(src, dst, encryptedDataKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_DecryptStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptStream'
type EncryptionService_DecryptStream_Call struct {
	*mock.Call
}

// DecryptStream is a helper method to define mock.On call
//   - src io.Reader
//   - dst io.Writer
//   - encryptedDataKey []byte
func (_e *EncryptionService_Expecter) DecryptStream(src interface{}, dst interface{}, encryptedDataKey interface{}) *EncryptionService_DecryptStream_Call {
	return &EncryptionService_DecryptStream_Call{Call: _e.mock.On("DecryptStream", src, dst, encryptedDataKey)}
}

func (_c *EncryptionService_DecryptStream_Call) Run(run func(src io.Reader, dst io.Writer, encryptedDataKey []byte)) *EncryptionService_DecryptStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(io.Writer), args[2].([]byte))
	})
	return _c
}

func (_c *EncryptionService_DecryptStream_Call) Return(_a0 error) *EncryptionService_DecryptStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_DecryptStream_Call) RunAndReturn(run func(io.Reader, io.Writer, []byte) error) *EncryptionService_DecryptStream_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptStream provides a mock function with given fields: src, dst
func (_m *EncryptionService) EncryptStream(src io.Reader, dst io.Writer) ([]byte, []byte, error) {
	ret := _m.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for EncryptStream")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(io.Reader, io.Writer) ([]byte, []byte, error)); ok {
		return rf(src, dst)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, io.Writer) []byte); ok {
		r0 = rf(src, dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, io.Writer) []byte); ok {
		r1 = rf(src, dst)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(io.Reader, io.Writer) error); ok {
		r2 = rf(src, dst)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// EncryptionService_EncryptStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptStream'
type EncryptionService_EncryptStream_Call struct {
	*mock.Call
}

// EncryptStream is a helper method to define mock.On call
//   - src io.Reader
//   - dst io.Writer
func (_e *EncryptionService_Expecter) EncryptStream(src interface{}, dst interface{}) *EncryptionService_EncryptStream_Call {
	return &EncryptionService_EncryptStream_Call{Call: _e.mock.On("EncryptStream", src, dst)}
}

func (_c *EncryptionService_EncryptStream_Call) Run(run func(src io.Reader, dst io.Writer)) *EncryptionService_EncryptStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(io.Writer))
	})
	return _c
}

func (_c *EncryptionService_EncryptStream_Call) Return(_a0 []byte, _a1 []byte, _a2 error) *EncryptionService_EncryptStream_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *EncryptionService_EncryptStream_Call) RunAndReturn(run func(io.Reader, io.Writer) ([]byte, []byte, error)) *EncryptionService_EncryptStream_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptStreamWithKey provides a mock function with given fields: src, dst, encryptedDataKey
func (_m *EncryptionService) EncryptStreamWithKey(src io.Reader, dst io.Writer, encryptedDataKey []byte) error {
	ret := _m.Called(src, dst, encryptedDataKey)

	if len(ret) == 0 {
		panic("no return value specified for EncryptStreamWithKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, io.Writer, []byte) error); ok {
		r0 = rf(src, dst, encryptedDataKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_EncryptStreamWithKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptStreamWithKey'
type EncryptionService_EncryptStreamWithKey_Call struct {
	*mock.Call
}

// EncryptStreamWithKey is a helper method to define mock.On call
//   - src io.Reader
//   - dst io.Writer
//   - encryptedDataKey []byte
func (_e *EncryptionService_Expecter) EncryptStreamWithKey(src interface{}, dst interface{}, encryptedDataKey interface{}) *EncryptionService_EncryptStreamWithKey_Call {
	return &EncryptionService_EncryptStreamWithKey_Call{Call: _e.mock.On("EncryptStreamWithKey", src, dst, encryptedDataKey)}
}

func (_c *EncryptionService_EncryptStreamWithKey_Call) Run(run func(src io.Reader, dst io.Writer, encryptedDataKey []byte)) *EncryptionService_EncryptStreamWithKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(io.Writer), args[2].([]byte))
	})
	return _c
}

func (_c *EncryptionService_EncryptStreamWithKey_Call) Return(_a0 error) *EncryptionService_EncryptStreamWithKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_EncryptStreamWithKey_Call) RunAndReturn(run func(io.Reader, io.Writer, []byte) error) *EncryptionService_EncryptStreamWithKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncryptionService creates a new instance of EncryptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptionService {
	mock := &EncryptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
